# Generated by Django 5.0.7 on 2024-07-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_current_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_method',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('overnight', 'Overnight')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
