# Generated by Django 5.0.7 on 2024-07-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_rename_tracking_number_delivery_delivery_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_id',
        ),
    ]
