# Generated by Django 5.0.7 on 2024-07-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_remove_delivery_delivery_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_provider',
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'Momo'), ('cash', 'Cash')], default='cash', max_length=255),
        ),
    ]
